name: Firebase CI/CD

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '22'
    - name: Install dependencies
      run: cd web && npm ci
    - name: Build
      run: cd web && npm run build --prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
        working-directory: web
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}