name: Firebase CI/CD

on:
  push:
    branches:
    - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '22'
    - name: Install dependencies
      run: cd web && npm ci
    - name: Build
      run: cd web && npm run build --prod
    - name: Deploy to Firebase Hosting
      run: cd web && npx firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}